
import { Button } from '../../../components/ui/button';
import { BrainCircuit, Variable, Code, Database } from 'lucide-react';

interface DynamicContentTabContentProps {
  handleDynamicContentClick: () => void;
  handleAIAssistantClick: () => void;
}

const DynamicContentTabContent = ({
  handleDynamicContentClick,
  handleAIAssistantClick
}: DynamicContentTabContentProps) => {
  const dynamicContentItems = [
    {
      id: 'variable',
      name: 'Variable',
      icon: <Variable className="h-4 w-4" />,
      description: 'Insert a dynamic variable that can be updated throughout the document'
    },
    {
      id: 'conditional',
      name: 'Conditional Block',
      icon: <Code className="h-4 w-4" />,
      description: 'Content that only appears when certain conditions are met'
    },
    {
      id: 'data-source',
      name: 'Data Connection',
      icon: <Database className="h-4 w-4" />,
      description: 'Connect to external data sources and display dynamic data'
    },
    {
      id: 'ai-block',
      name: 'AI-Generated Block',
      icon: <BrainCircuit className="h-4 w-4" />,
      description: 'Content that is dynamically generated by AI based on your prompt'
    }
  ];

  return (
    <>
      <div className="grid grid-cols-2 gap-4 mb-6">
        {dynamicContentItems.map((item) => (
          <div 
            key={item.id}
            className="border rounded-md p-4 cursor-pointer hover:border-blue-400 hover:bg-blue-50 transition"
            onClick={handleDynamicContentClick}
          >
            <div className="flex items-center mb-2">
              <div className="bg-blue-100 p-2 rounded-md text-blue-700 mr-3">
                {item.icon}
              </div>
              <h3 className="font-medium">{item.name}</h3>
            </div>
            <p className="text-sm text-gray-600">{item.description}</p>
          </div>
        ))}
      </div>
      
      <div className="bg-blue-50 border border-blue-200 rounded-md p-4 mb-4">
        <div className="flex items-start">
          <BrainCircuit className="h-5 w-5 text-blue-700 mr-3 mt-0.5" />
          <div>
            <h4 className="font-medium text-blue-800">AI-Powered Dynamic Content</h4>
            <p className="text-sm text-blue-700 mt-1">
              Dynamic content can be enhanced and updated by your connected AI assistant.
              All AI-driven changes are automatically tracked in version history.
            </p>
            <Button 
              variant="secondary" 
              size="sm" 
              className="mt-2 bg-blue-100 hover:bg-blue-200 border border-blue-300"
              onClick={handleAIAssistantClick}
            >
              <BrainCircuit className="h-4 w-4 mr-2" />
              Configure AI Assistant
            </Button>
          </div>
        </div>
      </div>
    </>
  );
};

export default DynamicContentTabContent;
