
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { lazy } from '../../../../shell/lazy';

// TODO: replace with ThinkWeb admin API
// Set VITE_THINKWEB_SUPABASE_URL / VITE_THINKWEB_SUPABASE_ANON_KEY in .env.local (never commit them).
// The shell shows a "not configured" state on ThinkWeb screens when they are missing.
const SUPABASE_URL: string = import.meta.env.VITE_THINKWEB_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY: string = import.meta.env.VITE_THINKWEB_SUPABASE_ANON_KEY ?? '';

// Import the supabase client like this:
// import { supabase } from "../../integrations/supabase/client";

// Created on first use (shell/lazy), so importing ThinkWeb never connects or throws.
export const supabase = lazy(() => createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
}));
