
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// TODO: replace with ThinkWeb admin API
// Set VITE_THINKWEB_SUPABASE_URL / VITE_THINKWEB_SUPABASE_ANON_KEY in .env.local (never commit them).
// Fallbacks keep the client constructible when unset; requests then fail inside ThinkWeb screens only.
const SUPABASE_URL: string = import.meta.env.VITE_THINKWEB_SUPABASE_URL || 'https://not-configured.supabase.co';
const SUPABASE_PUBLISHABLE_KEY: string = import.meta.env.VITE_THINKWEB_SUPABASE_ANON_KEY || 'not-configured';

// Import the supabase client like this:
// import { supabase } from "../../integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
